-- liquibase formatted sql

-- changeset David.Rabko:1_MED_210_Login
CREATE TABLE refresh_tokens
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token              VARCHAR(36)                              NOT NULL,
    user_id            BIGINT                                   NOT NULL,
    created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(50),
    last_modified_by   VARCHAR(50),
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE refresh_tokens;

-- changeset David.Rabko:2_MED_210_Login
CREATE TABLE verification_tokens
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token              VARCHAR(36)                              NOT NULL,
    user_id            BIGINT                                   NOT NULL,
    created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(50),
    last_modified_by   VARCHAR(50),
    CONSTRAINT verification_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE verification_tokens;

-- changeset David.Rabko:3_MED_210_Login
CREATE TABLE roles
(
    name VARCHAR(30) NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (name),
    UNIQUE (name)
);
-- rollback DROP TABLE roles;

-- changeset David.Rabko:4_MED_210_Login
CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enabled            BOOLEAN                                 NOT NULL DEFAULT FALSE,
    email              VARCHAR(50)                             NOT NULL UNIQUE,
    password           VARCHAR(255)                            NOT NULL,
    role               VARCHAR(30)                             NOT NULL,
    name               VARCHAR(50)                             NOT NULL,
    surname            VARCHAR(50)                             NOT NULL,
    birth_date         DATE                                    NOT NULL,
    created_date       TIMESTAMP                                        DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP                                        DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(50),
    last_modified_by   VARCHAR(50),
    street_address     VARCHAR(50),
    house              VARCHAR(20),
    apartment          VARCHAR(20),
    city               VARCHAR(50),
    state              VARCHAR(50),
    zip                VARCHAR(5),
    phone              VARCHAR(11),
    sex                VARCHAR(30),
    citizenship        VARCHAR(50),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    UNIQUE (email)
);
-- rollback DROP TABLE users;

-- changeset David.Rabko:8_MED_210_Login
ALTER TABLE refresh_tokens
    ADD CONSTRAINT refresh_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE refresh_tokens DROP CONSTRAINT refresh_tokens_users__fk;

-- changeset David.Rabko:9_MED_210_Login
ALTER TABLE refresh_tokens
    ADD CONSTRAINT verification_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE verification_tokens DROP CONSTRAINT verification_tokens_users__fk;

-- changeset David.Rabko:10_MED_210_Login
ALTER TABLE users
    ADD CONSTRAINT users_roles__fk FOREIGN KEY (role) REFERENCES roles (name) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE users DROP CONSTRAINT users_roles__fk;
