-- liquibase formatted sql

-- changeset David.Rabko:1_MED_210_Login
CREATE TABLE refresh_tokens
(
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token              VARCHAR(36)                              NOT NULL,
  user_id            BIGINT                                   NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT refresh_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE refresh_tokens;

-- changeset David.Rabko:2_MED_210_Login
CREATE TABLE verification_tokens
(
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token              VARCHAR(36)                              NOT NULL,
  user_id            BIGINT                                   NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT verification_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE verification_tokens;

-- changeset David.Rabko:3_MED_210_Login
CREATE TABLE roles
(
  name VARCHAR(30) NOT NULL,
  CONSTRAINT role_pkey PRIMARY KEY (name),
  UNIQUE (name)
);
-- rollback DROP TABLE roles;

-- changeset David.Rabko:4_MED_210_Login
CREATE TABLE users
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  enabled            BOOLEAN                                 NOT NULL DEFAULT FALSE,
  email              VARCHAR(50)                             NOT NULL UNIQUE,
  password           VARCHAR(255)                            NOT NULL,
  role               VARCHAR(30)                             NOT NULL,
  person_id          BIGINT                                  NOT NULL,
  created_date       TIMESTAMP                                        DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP                                        DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  UNIQUE (email)
);
-- rollback DROP TABLE users;

-- changeset David.Rabko:8_MED_210_Login
ALTER TABLE refresh_tokens
  ADD CONSTRAINT refresh_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE refresh_tokens DROP CONSTRAINT refresh_tokens_users__fk;

-- changeset David.Rabko:9_MED_210_Login
ALTER TABLE verification_tokens
  ADD CONSTRAINT verification_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE verification_tokens DROP CONSTRAINT verification_tokens_users__fk;

-- changeset David.Rabko:10_MED_210_Login
ALTER TABLE users
  ADD CONSTRAINT users_roles__fk FOREIGN KEY (role) REFERENCES roles (name) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE users DROP CONSTRAINT users_roles__fk;

-- changeset David.Rabko:11_MED_223_Reset_password
CREATE TABLE one_time_passwords
(
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token              VARCHAR(4)                               NOT NULL,
  user_id            BIGINT                                   NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT password_reset_token_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE password_reset_tokens;

-- changeset David.Rabko:12_MED_223_Reset_password
ALTER TABLE one_time_passwords
  ADD CONSTRAINT password_reset_tokens_users__fk FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE password_reset_tokens DROP CONSTRAINT password_reset_tokens_users__fk;

-- changeset Uladzislau.Lukashevich:12_MED_143_Location
CREATE TABLE locations
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  hospital_name      VARCHAR(50)                             NOT NULL,
  street_address     VARCHAR(50)                             NOT NULL,
  house              VARCHAR(20)                             NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT location_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE locations;

-- changeset Uladzislau.Lukashevich:13_MED_145_Patient
CREATE TABLE patients
(
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  checkbox_terms_and_conditions BOOLEAN                                 NOT NULL,
  CONSTRAINT patient_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE patients;


-- changeset Uladzislau.Lukashevich:16_MED_142_Doctor
CREATE TABLE specializations
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  specialization     VARCHAR(50)                             NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT specialization_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE specializations;

-- changeset Uladzislau.Lukashevich:17_MED_142_Doctor
CREATE TABLE doctors
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  license_number VARCHAR(100)                            NOT NULL,
  location_id    BIGINT                                  NOT NULL,
  CONSTRAINT doctor_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE doctors;

-- changeset Uladzislau.Lukashevich:18_MED_142_Doctor
CREATE TABLE doctors_specializations_bridge
(
  doctor_id          BIGINT NOT NULL,
  specializations_id BIGINT NOT NULL,
  CONSTRAINT doctors_specializations_bridge_pkey PRIMARY KEY (doctor_id, specializations_id)
);
-- rollback DROP TABLE doctors_specialization_bridge;

-- changeset Uladzislau.Lukashevich:19_MED_142_Doctor
ALTER TABLE doctors_specializations_bridge
  ADD CONSTRAINT doctors_specializations_bridge_doctors__fk FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors_specializations_bridge DROP CONSTRAINT doctors_specializations_bridge_doctors__fk;

-- changeset Uladzislau.Lukashevich:20_MED_142_Doctor
ALTER TABLE doctors_specializations_bridge
  ADD CONSTRAINT doctors_specializations_bridge_specializations__fk FOREIGN KEY (specializations_id) REFERENCES specializations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors_specializations_bridge DROP CONSTRAINT doctors_specializations_bridge_specializations__fk;

-- changeset Uladzislau.Lukashevich:23_MED_144_Appointment
CREATE TABLE appointment_statuses
(
  status VARCHAR(25) NOT NULL,
  CONSTRAINT status_pkey PRIMARY KEY (status),
  UNIQUE (status)
);
-- rollback DROP TABLE statuses;

-- changeset Uladzislau.Lukashevich:24_MED_144_Appointment
CREATE TABLE consultation_appointments
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  doctor_id          BIGINT                                  NOT NULL,
  patient_id         BIGINT                                  NOT NULL,
  service_id         BIGINT                                  NOT NULL,
  date_from          TIMESTAMP                               NOT NULL,
  date_to            TIMESTAMP                               NOT NULL,
  location_id        BIGINT,
  type               VARCHAR(10)                             NOT NULL,
  appointment_status VARCHAR(30)                             NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  CONSTRAINT consultation_appointment_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE consultation_appointments;

-- changeset Uladzislau.Lukashevich:25_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_appointment_statuses__fk FOREIGN KEY (appointment_status) REFERENCES appointment_statuses (status) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_appointment_statuses__fk;

-- changeset Uladzislau.Lukashevich:26_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_doctors__fk FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_doctors__fk;

-- changeset Uladzislau.Lukashevich:27_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_patients__fk FOREIGN KEY (patient_id) REFERENCES patients (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_patients__fk;

-- changeset Uladzislau.Lukashevich:28_MED_144_Appointment
ALTER TABLE consultation_appointments
  ADD CONSTRAINT consultation_appointments_locations__fk FOREIGN KEY (location_id) REFERENCES locations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE consultation_appointments DROP CONSTRAINT consultation_appointments_locations__fk;

-- changeset Uladzislau.Lukashevich:34_MED_140_Appointment_Endpoint
CREATE TABLE persons
(
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name               VARCHAR(50)                             NOT NULL,
  surname            VARCHAR(50)                             NOT NULL,
  birth_date         DATE                                    NOT NULL,
  created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by         VARCHAR(50),
  last_modified_by   VARCHAR(50),
  street_address     VARCHAR(50),
  house              VARCHAR(20),
  apartment          VARCHAR(20),
  city               VARCHAR(50),
  state              VARCHAR(50),
  zip                VARCHAR(5),
  phone              VARCHAR(11),
  sex                VARCHAR(30),
  citizenship        VARCHAR(50),

  CONSTRAINT person_pkey PRIMARY KEY (id)
);
-- rollback DROP TABLE persons;

-- changeset Uladzislau.Lukashevich:35_MED_140_Appointment_Endpoint
ALTER TABLE users
  ADD CONSTRAINT users_persons__fk FOREIGN KEY (person_id) REFERENCES persons (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE users DROP CONSTRAINT users_persons__fk;

-- changeset Uladzislau.Lukashevich:36_MED_140_Appointment_Endpoint
ALTER TABLE patients
  ADD CONSTRAINT patients_persons__fk FOREIGN KEY (id) REFERENCES persons (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE patients DROP CONSTRAINT patients_persons__fk;

-- changeset Uladzislau.Lukashevich:37_MED_140_Appointment_Endpoint
ALTER TABLE doctors
  ADD CONSTRAINT doctors_persons__fk FOREIGN KEY (id) REFERENCES persons (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors DROP CONSTRAINT doctors_persons__fk;

-- changeset Uladzislau.Lukashevich:38_MED_140_Appointment_Endpoint
ALTER TABLE doctors
  ADD CONSTRAINT doctors_locations__fk FOREIGN KEY (location_id) REFERENCES locations (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
-- rollback ALTER TABLE doctors DROP CONSTRAINT doctors_location__fk;
